
@URL_BASE = http://localhost:8080

### obter todas as pessoas
GET {{URL_BASE}}/pessoa

### cadastrar pessoa
POST {{URL_BASE}}/pessoa
Content-Type: 'application/json'
{   
    "nome":"ze Pitanga",
    "mail":"ze@hotmail.com",
    "nascimento":"1960-01-01T00:00"


}