version: "3"

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_agencia
       
    ports:
      - $MARIADB_LOCAL_PORT:$MARIADB_DOCKER_PORT
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  mariadb:


#docker run --name mariadb -e MYSQL_ROOT_PASSWORD=root -p 3306:3306 -d docker.io/library/mariadb
#docker exec -it mariadb bash
# apt-get update
# apt-get install mysql-server
# mysql -u root -p
# DROP DATABASE db_agencia;
# CREATE DATABASE db_agencia;

