@URL_BASE=http://localhost:8080

###Obter todos os pacotes
GET {{URL_BASE}}/auth

### Cadastrar 1 usuário
POST {{URL_BASE}}/auth
Content-Type: application/json

{
    "username" : "fabiano-smi@gmail.com",
    "password" : "medianeira1234"
}