@URL_BASE=http://localhost:8080

@TOKEN= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VybmFtZSI6ImZhYmlhbm8tc21pQGhvdG1haWwuY29tIiwiaWF0IjoxNzAxNTk3NzkwLCJleHAiOjE3MDE2MDEzOTAsImlzcyI6IlVURlBSIn0.U8R---AP-3OIG7Zw2pF8OANjlRpwzknfxCCVcTw2bEw

###Obter todas as pessoas
GET {{URL_BASE}}/pessoa
Authorization: Bearer {{TOKEN}}

###Obter todas as pessoas cm token
GET {{URL_BASE}}/pessoa/token/{{TOKEN}}
Authorization: Bearer {{TOKEN}}

###Obter todas as pessoas por pagina
GET {{URL_BASE}}/pessoa/pages?size=20&page=0&sort=email&direction=DESC
Authorization: Bearer {{TOKEN}}

###Obter uma pessoa
GET {{URL_BASE}}/pessoa/e7ca0443-c64d-41e6-897d-fc97f2dd39e6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VybmFtZSI6ImZhYmlhbm8tc21pQGhvdG1haWwuY29tIiwiaWF0IjoxNzAwODQ2MjM4LCJleHAiOjE3MDA4NDk4MzgsImlzcyI6IlVURlBSIn0.4k9AYPrLIJ-QiyIE1zy7se7aPsxsJQe5W2QNhcL8ZFU

### Cadastrar 1 pessoa
POST {{URL_BASE}}/pessoa
Content-Type: application/json

{
    "nome": "fabiano",
    "email": "fabiano-smi@gmail.com",
    "telefone": "+5545998217562",
    "dataAniversario": "1991-03-04",
    "identificacao": "cliente",
    "senha": "medianeira123"
}

### Atualizar 1 pessoa
PUT {{URL_BASE}}/pessoa/071b699bd6-f2af-41ab-8bdf-22d00b0c1fe0
Content-Type: application/json

{
    "nome": "Douglas Marcondes",
    "email": "douglasc@alunos.utfpr.edu.br",
    "telefone": "+5545998217562",
    "dataAniversario": "1991-03-04",
    "identificacao": "admnistrador",
    "senha": "natal123"
}



### Deletar 1 pesso
DELETE {{URL_BASE}}/pessoa/e7ca0443-c64d-41e6-897d-fc97f2dd39e6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VybmFtZSI6ImZhYmlhbm8tc21pQGhvdG1haWwuY29tIiwiaWF0IjoxNzAwODQ2MjM4LCJleHAiOjE3MDA4NDk4MzgsImlzcyI6IlVURlBSIn0.4k9AYPrLIJ-QiyIE1zy7se7aPsxsJQe5W2QNhcL8ZFU

{

}