@URL_BASE=http://localhost:8080
@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VybmFtZSI6ImNsaWVudGVAaG90bWFpbC5jb20iLCJpYXQiOjE3MDE2MDc1MzgsImV4cCI6MTcwMTYxMTEzOCwiaXNzIjoiVVRGUFIifQ.nDeAnkk-co--t66rFMaYfV5t6CiOYJ6AY8cN5vx79BA 
###Obter todas as reservas
GET {{URL_BASE}}/reserva
Authorization: Bearer {{TOKEN}}

###Obter todas as pessoas por pagina
GET {{URL_BASE}}/reserva/pages?size=20&page=0&sort=data&direction=DESC

###Obter uma reserva
GET {{URL_BASE}}/reserva/07f609d7-a8ad-49e0-bc87-bdae624ec20b

### Cadastrar 1 reserva
POST {{URL_BASE}}/reserva
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "pacote" : { "id" : "2a0a9ad0-8410-4993-b541-183fee6ae1cb"},
    "pessoa" : { "id" : "e16b762b-ad6a-4006-b630-07d1ccb12494"},
    "data"   : "2023-09-15T22:24:00"
}

### Atualizar 1 reserva
PUT {{URL_BASE}}/reserva/07d51ac6-9f73-43da-8725-ae2edc4d458d
Content-Type: application/json

{
    "pacote" : { "id" : ""},
    "pessoa" : { "id" : ""},
    "data"   : "2023-09-15T22:24:00"
}



### Deletar 1 reserva
DELETE {{URL_BASE}}/reserva/4f2b6a6b-0762-4df4-bab9-115d2768cad5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VybmFtZSI6ImNsaWVudGVAaG90bWFpbC5jb20iLCJpYXQiOjE3MDE2MDY1NTgsImV4cCI6MTcwMTYxMDE1OCwiaXNzIjoiVVRGUFIifQ.YAN2nlKGrcFP16J3vCBk5jDw4PMP_XZs3kpeP-b6YFU
 