version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - bridge

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_agencia
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - bridge

networks:
  bridge:
    driver: bridge

volumes:
  mongodb:  
  mariadb:


  #docker run --name mariadb -e MYSQL_ROOT_PASSWORD=root -p 3306:3306 -d docker.io/library/mariadb
  #docker exec -it mariadb bash
  # apt-get update
  # apt-get install mysql-server
  # mysql -u root -p
  # DROP DATABASE db_agencia;
  # CREATE DATABASE db_agencia;


  #npm run build